### ISSUE TITLE
Criar backend para dados do Brasil

### ISSUE THREAD

**Issue by LuisHenrique01** [IFPiaui/covid19-map#1]
## Fazer scrap de dados do brasil e salvar em banco
* Pegar dados de fontes oficiais
* Salvar em banco 
* Salvar estado no formato pronto para carregar no highmaps <https://jsfiddle.net/gh/get/jquery/1.11.0/highslide-software/highcharts.com/tree/master/samples/mapdata/countries/br/br-all>

**Comment by webalysson** [comment]
A código que postei para gerar a série pode ser adaptado para gerar de todo o Brasil, devemos apenas aplicar os devidos filtros na requisição a API do Brasil.io, outra forma para o cenário Brasil seria o .csv disponibilizado diariamente pelo Ministério da Saúde.
